// SPDX-License-Identifier: Apache-2.0
//
// PRODUCTION BRIDGE-WRITER end-to-end proof (PR-23, #1436/#1440).
//
// THE LOAD-BEARING DIFFERENCE from `cmd_verify_body_discharge.rs`: that
// test HAND-BUILDS the `.proof` bundle -- it hand-writes the op-contract
// member AND the `sourceSymbol -> targetContractCid` bridge, then drives
// `verify`. It proves the SEAM works when something upstream wrote the
// bridge. It does NOT prove anything upstream actually writes it.
//
// This test closes that gap. It drives the REAL `sugar mint` CLI binary
// against a body-derived `function-contract` ir-document (the shape walk /
// JavaSourceLifter emit) and asserts the TOOL -- not the test -- wrote the
// bridge into the bundle. Then it drives the REAL `sugar verify` CLI on
// that tool-minted bundle and asserts the double discharges both ways:
//
//   POSITIVE: `double(x) = x*2`, harvested `assert_eq!(double(3), 6)`.
//     mint auto-writes the bridge `double -> <op-contract>`; verify reduces
//     `double(3)==6` through the body `x*2` -> `*(3,2)==6` -> z3 discharges
//     -> pass, signed witness, exit 0.
//
//   NEGATIVE: break the body to `x*3`. verify reduces to `*(3,3)==6` ->
//     z3 refutes -> Unsatisfied, exit 1, NO witness.
//
// The mint path is exercised through the genuine lift-plugin RPC: a mock
// lifter (a tiny shell script generated by the test) speaks the
// newline-delimited JSON-RPC the production `LiftPluginKit` expects
// (initialize / lift / shutdown), and returns the `ir-document`. This is
// the identical code path a real rust/java lifter drives -- the lifter is
// upstream of and orthogonal to the bridge-writer, so a mock lifter
// faithfully exercises the production mint+bridge logic without requiring
// charon/javac in the test environment.
//
// Requires `z3` on PATH; skips the solver-dependent asserts otherwise.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{json, Value as Json};

fn sugar_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_sugar"))
}

fn z3_available() -> bool {
    Command::new("z3")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn unique_dir(suffix: &str) -> PathBuf {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let p = std::env::temp_dir().join(format!("sugar-prod-bridge-{stamp}-{suffix}"));
    fs::create_dir_all(&p).expect("mkdir project");
    p
}

fn install_smt_compiler_manifest(project: &Path) {
    let manifest_dir = project.join(".sugar").join("ir-compilers").join("smt-lib");
    fs::create_dir_all(&manifest_dir).expect("mkdir ir compiler manifest");
    let rust_workspace = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("sugar-cli has a parent workspace");
    fs::write(
        manifest_dir.join("manifest.toml"),
        format!(
            r#"name = "smt-lib-reference"
version = "0.1.0"
protocol_version = "sugar-ir-compiler/1"
command = ["cargo", "run", "-p", "sugar-ir-compiler-smt-lib", "--bin", "sugar-ir-smt-lib", "--quiet", "--"]
working_dir = "{}"
dialects = ["smt-lib-v2.6"]
"#,
            rust_workspace.display()
        ),
    )
    .expect("write ir compiler manifest");
}

/// An Int-sorted IR const term.
fn int_const(n: i64) -> Json {
    json!({"kind": "const", "value": n, "sort": {"kind": "primitive", "name": "Int"}})
}

/// Build the `ir-document` the lifter returns: a body-derived
/// `function-contract` for `double` plus the harvested source contract
/// carrying `assert_eq!(double(3), 6)`. `body_factor` is the multiplier in
/// the body (`x * body_factor`); 2 is the honest body, 3 the broken one.
///
/// This is exactly the shape walk's `build_function_contract` ->
/// `mint_args` emits (and JavaSourceLifter, once `return_value` is renamed
/// to `result`): `function-contract` with `formals`, `formalSorts`, and
/// `post = (result == *(x, k))`. The harvested assertion is a `contract`
/// with `inv = =(double(3), 6)`. NO bridge -- the TOOL must write that.
fn ir_document(body_factor: i64) -> Json {
    json!({
        "kind": "ir-document",
        "diagnostics": [],
        "ir": [
            {
                "kind": "function-contract",
                "fn_name": "double",
                "formals": ["x"],
                "formalSorts": [{"kind": "primitive", "name": "Int"}],
                "returnSort": {"kind": "primitive", "name": "Int"},
                "outBinding": "result",
                "post": {
                    "kind": "atomic", "name": "=",
                    "args": [
                        {"kind": "var", "name": "result"},
                        {"kind": "ctor", "name": "*", "args": [
                            {"kind": "var", "name": "x"},
                            int_const(body_factor)
                        ]}
                    ]
                }
            },
            {
                "kind": "contract",
                "symbol": "double_test",
                "outBinding": "out",
                "inv": {
                    "kind": "atomic", "name": "=",
                    "args": [
                        {"kind": "ctor", "name": "double", "args": [int_const(3)]},
                        int_const(6)
                    ]
                }
            }
        ]
    })
}

/// Build the zero-arg `ir-document` variant: a body-derived
/// `function-contract` for `answer()` plus a harvested source assertion
/// carrying `assert_eq!(answer(), 42)`. This is the empty-formals corner of
/// the same production bridge-writer seam: zero parameters still means
/// body-bearing, so mint must promote it into a bridge member.
fn zero_arg_ir_document(body_value: i64) -> Json {
    json!({
        "kind": "ir-document",
        "diagnostics": [],
        "ir": [
            {
                "kind": "function-contract",
                "fn_name": "answer",
                "formals": [],
                "formalSorts": [],
                "returnSort": {"kind": "primitive", "name": "Int"},
                "outBinding": "result",
                "post": {
                    "kind": "atomic", "name": "=",
                    "args": [
                        {"kind": "var", "name": "result"},
                        int_const(body_value)
                    ]
                }
            },
            {
                "kind": "contract",
                "symbol": "answer_test",
                "outBinding": "out",
                "inv": {
                    "kind": "atomic", "name": "=",
                    "args": [
                        {"kind": "ctor", "name": "answer", "args": []},
                        int_const(42)
                    ]
                }
            }
        ]
    })
}

/// Generate a mock lift-plugin RPC: a POSIX shell script that speaks the
/// newline-delimited JSON-RPC `LiftPluginKit` drives. It replies to
/// `initialize` (id 1) and `lift` (id 2, result = the ir-document), then
/// exits on `shutdown`. The ir-document is baked into the script body so
/// the lifter is fully self-contained.
fn write_mock_lifter_with_ir(project: &Path, surface: &str, ir_doc: Json) -> PathBuf {
    let lift_dir = project.join(".sugar").join("lift").join(surface);
    fs::create_dir_all(&lift_dir).expect("mkdir lift surface dir");

    // The lift `result` is the ir-document. Embed it as a single JSON line.
    // The mock RPC reads each JSON-RPC line; on `initialize` emit an
    // initialize result, on `lift` emit the ir-document result, on
    // `shutdown` exit. Newline-delimited, exactly what `read_response`
    // parses (one JSON object per line, matching the request `id`).
    let init_result = json!({
        "jsonrpc": "2.0",
        "id": 1,
        "result": {"name": surface, "protocol_version": "pep/1.7.0"}
    });
    let lift_result = json!({"jsonrpc": "2.0", "id": 2});
    // Build the lift response with the embedded ir-document as `result`.
    let mut lift_obj = lift_result.as_object().unwrap().clone();
    lift_obj.insert("result".into(), ir_doc.clone());
    let lift_line = serde_json::to_string(&Json::Object(lift_obj)).expect("serialize lift result");
    let init_line = serde_json::to_string(&init_result).expect("serialize init result");

    let script = format!(
        r#"#!/bin/sh
# Mock lift-plugin RPC for the production-bridge gauntlet (PR-23).
# Newline-delimited JSON-RPC: reply to initialize (id 1) and lift (id 2),
# exit on shutdown. Single-shot: one initialize, one lift, one shutdown.
while IFS= read -r line; do
  case "$line" in
    *'"method":"initialize"'*|*'"method": "initialize"'*)
      printf '%s\n' '{init_line}'
      ;;
    *'"method":"lift"'*|*'"method": "lift"'*)
      printf '%s\n' '{lift_line}'
      ;;
    *'"method":"shutdown"'*|*'"method": "shutdown"'*)
      exit 0
      ;;
  esac
done
"#,
        init_line = init_line.replace('\'', "'\\''"),
        lift_line = lift_line.replace('\'', "'\\''"),
    );

    let script_path = lift_dir.join("mock-lifter.sh");
    fs::write(&script_path, script).expect("write mock lifter script");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&script_path).unwrap().permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&script_path, perms).expect("chmod mock lifter");
    }

    let manifest = format!(
        "name = \"{surface}\"\ncommand = [\"{}\"]\nworking_dir = \".\"\n",
        script_path.display()
    );
    fs::write(lift_dir.join("manifest.toml"), manifest).expect("write manifest.toml");
    script_path
}

/// Build a project whose lift produces the body-derived double contract,
/// run the REAL `sugar mint` CLI, and return (project_dir, proof_path).
/// `body_factor` is the body multiplier (2 = honest, 3 = broken).
fn mint_project_from_ir(suffix: &str, ir_doc: Json) -> (PathBuf, PathBuf) {
    let surface = "mock";
    let project = unique_dir(suffix);
    fs::create_dir_all(project.join(".sugar")).expect("mkdir .sugar");
    install_smt_compiler_manifest(&project);
    // A real kit's config.toml declares its lift surface and may declare its
    // solver plan. This fixture keeps an explicit z3 plan so the production
    // bridge test exercises configured solver dispatch. The `-smt2 -in` flags
    // mirror `registry::build_default_z3`; keep in sync if that fallback
    // changes.
    fs::write(
        project.join(".sugar").join("config.toml"),
        format!(
            "[authoring]\nsurface = \"{surface}\"\n\n\
             [solvers]\ndefault = \"z3\"\n\n\
             [solvers.dispatch]\nlinear_arithmetic = \"z3\"\ndefault = \"z3\"\n\n\
             [solvers.z3]\nbinary = \"z3\"\nir_compiler = \"smt-lib-v2.6\"\nflags = [\"-smt2\", \"-in\"]\n"
        ),
    )
    .expect("write config.toml");
    write_mock_lifter_with_ir(&project, surface, ir_doc);

    let out = Command::new(sugar_bin())
        .arg("mint")
        .arg("--project")
        .arg(&project)
        .arg("--out")
        .arg(&project)
        .arg("--quiet")
        .output()
        .expect("spawn sugar mint");
    assert!(
        out.status.success(),
        "sugar mint must succeed\n  stdout: {}\n  stderr: {}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );

    // Locate the produced .proof in the project dir.
    let proof = fs::read_dir(&project)
        .expect("read project dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .find(|p| p.extension().map(|x| x == "proof").unwrap_or(false))
        .unwrap_or_else(|| panic!("mint must write a .proof into {}", project.display()));
    (project, proof)
}

fn mint_double_project(suffix: &str, body_factor: i64) -> (PathBuf, PathBuf) {
    mint_project_from_ir(suffix, ir_document(body_factor))
}

/// Load the tool-minted bundle through the verifier's stage-1 loader. The
/// returned pool keys `mementos` by member CID -- the same map the seam's
/// `CatalogResolver` resolves `bridge.targetContractCid` against.
fn pool_of_project(project: &Path) -> sugar_verifier::types::MementoPool {
    let pool = sugar_verifier::load_all_proofs::run(project);
    assert!(
        pool.load_errors.is_empty(),
        "tool-minted bundle must load cleanly: {:?}",
        pool.load_errors
    );
    pool
}

fn run_verify_json_with_code(project: &Path, witness_dir: &Path) -> (Json, i32) {
    let out = Command::new(sugar_bin())
        .arg("verify")
        .arg("--project")
        .arg(project)
        .arg("--emit-witnesses")
        .arg(witness_dir)
        .arg("--json")
        .output()
        .expect("spawn sugar verify");
    let stdout = String::from_utf8_lossy(&out.stdout);
    let receipt = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("verify JSON parse failed: {e}\nstdout: {stdout}"));
    (receipt, out.status.code().unwrap_or(-1))
}

/// THE bridge-writer assertion (language-neutral, runs without z3): the
/// TOOL wrote a `bridge` member for `double` whose `targetContractCid`
/// resolves to a `contract` member carrying the body-derived `formals` +
/// `post`. No hand-bridging anywhere in this test.
#[test]
fn mint_auto_writes_body_discharge_bridge() {
    let (project, _proof) = mint_double_project("bridge", 2);
    let pool = pool_of_project(&project);

    // mint auto-indexed the bridge by sourceSymbol (the same index
    // `enumerate_callsites` consults). The TOOL wrote this, not the test.
    let bridge = pool.bridges_by_symbol.get("double").unwrap_or_else(|| {
        panic!(
            "mint must auto-write + index a bridge with sourceSymbol=double; indexed symbols: {:?}",
            pool.bridges_by_symbol.keys().collect::<Vec<_>>()
        )
    });

    let target_cid = sugar_proof_envelope::member_field(bridge, "targetContractCid")
        .and_then(|v| v.as_str())
        .expect("bridge must carry targetContractCid")
        .to_string();

    // That target CID must resolve (by member-CID key, exactly as
    // CatalogResolver does) to a contract carrying the body-derived
    // formals + post.
    let _ = pool.mementos.get(&target_cid).unwrap_or_else(|| {
        panic!(
            "bridge.targetContractCid {target_cid} must resolve to a member; member CIDs: {:?}",
            pool.mementos.keys().collect::<Vec<_>>()
        )
    });
    assert_eq!(
        pool.member_kind(&target_cid),
        Some("contract"),
        "bridge target must be a contract memento"
    );
    let formals = pool.member_field(&target_cid, "formals")
        .and_then(|v| v.as_array())
        .expect("tool-written op-contract must carry formals (delta 2)");
    assert_eq!(
        formals.first().and_then(|v| v.as_str()),
        Some("x"),
        "op-contract formals must be [x]"
    );
    assert!(
        pool.member_field(&target_cid, "post").is_some(),
        "op-contract must carry the body-derived post"
    );

    let _ = fs::remove_dir_all(&project);
}

/// Empty `formals` is still body-bearing. The production bridge writer must
/// promote a zero-arg `function-contract` into the same bridge index that
/// `enumerate_callsites` uses; otherwise verify reports `totalClaims: 0`
/// for a real harvested `answer()` assertion.
#[test]
fn mint_auto_writes_zero_arg_body_discharge_bridge() {
    let (project, _proof) = mint_project_from_ir("zeroarg-bridge", zero_arg_ir_document(42));
    let pool = pool_of_project(&project);

    let bridge = pool.bridges_by_symbol.get("answer").unwrap_or_else(|| {
        panic!(
            "mint must auto-write + index a bridge with sourceSymbol=answer; indexed symbols: {:?}",
            pool.bridges_by_symbol.keys().collect::<Vec<_>>()
        )
    });

    let target_cid = sugar_proof_envelope::member_field(bridge, "targetContractCid")
        .and_then(|v| v.as_str())
        .expect("bridge must carry targetContractCid")
        .to_string();
    let _ = pool.mementos.get(&target_cid).unwrap_or_else(|| {
        panic!(
            "bridge.targetContractCid {target_cid} must resolve to a member; member CIDs: {:?}",
            pool.mementos.keys().collect::<Vec<_>>()
        )
    });
    let formals = pool.member_field(&target_cid, "formals")
        .and_then(|v| v.as_array())
        .expect("zero-arg op-contract must carry an explicit formals array");
    assert!(
        formals.is_empty(),
        "zero-arg op-contract formals must stay empty; got {formals:?}"
    );
    assert!(
        pool.member_field(&target_cid, "post").is_some(),
        "zero-arg op-contract must carry the body-derived post"
    );

    if z3_available() {
        let witnesses = project.join("witnesses-out");
        let (receipt, code) = run_verify_json_with_code(&project, &witnesses);
        assert_eq!(
            receipt["totalClaims"], 1,
            "zero-arg harvested answer() assertion must enumerate; receipt: {receipt}"
        );
        let claim = &receipt["claims"].as_array().expect("claims")[0];
        assert_eq!(
            claim["pass"], true,
            "answer()==42 must discharge through zero-arg body; claim: {claim}"
        );
        assert_eq!(claim["status"], "discharged", "claim: {claim}");
        assert_eq!(receipt["ok"], true, "receipt: {receipt}");
        assert_eq!(code, 0, "zero-arg positive run exits clean; got {code}");
    } else {
        eprintln!("z3 not on PATH: skipping zero-arg production-bridge verify assertion");
    }

    let _ = fs::remove_dir_all(&project);
}

/// POSITIVE end-to-end: tool-written bridge, verify discharges through the
/// body `x*2`, signed witness, exit 0.
#[test]
fn production_path_double_discharges_and_mints_witness() {
    if !z3_available() {
        eprintln!("z3 not on PATH: skipping production-bridge positive test");
        return;
    }
    let (project, _proof) = mint_double_project("pos", 2);
    let witnesses = project.join("witnesses-out");
    let (receipt, code) = run_verify_json_with_code(&project, &witnesses);

    assert_eq!(
        receipt["kind"], "verification-receipt",
        "receipt: {receipt}"
    );
    assert_eq!(
        receipt["totalClaims"], 1,
        "exactly one body-bearing callsite (the tool-written bridge made `double(3)` enumerate); receipt: {receipt}"
    );
    let claim = &receipt["claims"].as_array().expect("claims")[0];
    assert_eq!(
        claim["pass"], true,
        "double(3)==6 must discharge through body x*2; claim: {claim}"
    );
    assert_eq!(claim["status"], "discharged", "claim: {claim}");

    let solver = claim["dischargingSolver"].as_str().unwrap_or("");
    assert!(
        solver.starts_with("z3@"),
        "discharging solver must be z3; got `{solver}`"
    );

    let witness_cid = claim["witnessCid"].as_str().expect("witness minted");
    assert!(witness_cid.starts_with("blake3-512:"));
    // Captured for the #1436/#1440 report:
    //   cargo test production_path_double_discharges -- --nocapture
    eprintln!("PRODUCTION_POSITIVE_WITNESS_CID={witness_cid}");

    assert_eq!(receipt["ok"], true, "receipt: {receipt}");
    assert_eq!(code, 0, "positive run exits clean; got {code}");

    let _ = fs::remove_dir_all(&project);
}

/// NEGATIVE end-to-end: broken body `x*3`, verify Unsatisfied, exit 1, no
/// witness. The decisive proof the tool-written bridge does not vacuously
/// pass: a real violation is caught honestly.
#[test]
fn production_path_broken_body_fails_unsatisfied_no_witness() {
    if !z3_available() {
        eprintln!("z3 not on PATH: skipping production-bridge negative test");
        return;
    }
    let (project, _proof) = mint_double_project("neg", 3);
    let witnesses = project.join("witnesses-out");
    let (receipt, code) = run_verify_json_with_code(&project, &witnesses);

    assert_eq!(receipt["totalClaims"], 1, "receipt: {receipt}");
    let claim = &receipt["claims"].as_array().expect("claims")[0];
    assert_eq!(
        claim["status"], "unsatisfied",
        "broken body x*3 must be UNSATISFIED (not undecidable); claim: {claim}"
    );
    assert_eq!(claim["pass"], false, "claim: {claim}");
    assert!(
        claim["witnessCid"].is_null(),
        "no witness for a violated claim; claim: {claim}"
    );
    assert_eq!(receipt["ok"], false, "receipt: {receipt}");

    let witness_files: Vec<_> = fs::read_dir(&witnesses)
        .map(|rd| rd.filter_map(|e| e.ok()).collect())
        .unwrap_or_default();
    assert!(
        witness_files.is_empty(),
        "witness dir must be empty for a violated claim; found {} files",
        witness_files.len()
    );

    assert_eq!(
        code, 1,
        "broken-body claim must exit 1 (EXIT_VERIFY_FAIL, not 3=undecidable); got {code}"
    );
    eprintln!(
        "PRODUCTION_NEGATIVE_EXIT_CODE={code} STATUS={}",
        claim["status"]
    );

    let _ = fs::remove_dir_all(&project);
}
