//! Committed-artifact integrity gate.
//!
//! Every file whose name is a CID -- `blake3-512:<128hex>[.ext]`, a proof stem
//! `blake3-512_<128hex>[.ext]`, or a bare `<128hex>[.ext]` -- is a
//! content-addressed artifact. For most classes, its name is the blake3-512 of
//! the committed bytes. A few historical bind-inventory classes were generated
//! under explicit canonical-JSON disciplines; those are verified below by
//! recomputing the exact generator rule, not by exempting the files.
//!
//! The acid-test gate never notices, because it RE-MINTS proofs rather than
//! loading the committed ones. This test loads them: it walks the repo and
//! asserts every CID-named file still verifies under its named discipline. It is the
//! standing regression guard for the Sugar cutover, which mangled 8 `.proof`
//! bundles (PR #1966) before PR #1970 restored them. Add no bypasses: every
//! accepted file must match one named discipline exactly.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value};
use sugar_canonicalizer::{blake3_512_of, jcs_cid_of_json};
use sugar_proof_envelope::cid_from_proof_stem;

const SKIP_DIRS: &[&str] = &[
    "target",
    ".git",
    ".jj",
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .find(|p| p.join("implementations/rust").is_dir())
        .expect("repo root: an ancestor containing implementations/rust")
        .to_path_buf()
}

/// The CID a content-addressed filename claims, or `None` if the name is not a
/// CID. Accepts the prefixed (`blake3-512:<hex>`), proof-stem
/// (`blake3-512_<hex>`), and bare (`<hex>`) forms; the hex is the stem before
/// the first extension dot and must be exactly 128 chars. This rejects e.g.
/// `invalid-filename-cid.proof` (a deliberate negative fixture) whose stem is
/// not 128 hex.
fn claimed_cid(file_name: &str) -> Option<String> {
    let stem = file_name.split('.').next().unwrap_or("");
    cid_from_proof_stem(stem)
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if path.is_dir() {
            if !SKIP_DIRS.contains(&name.as_ref()) {
                collect(&path, out);
            }
        } else if claimed_cid(&name).is_some() {
            out.push(path);
        }
    }
}

#[derive(Debug)]
struct DisciplineAttempt {
    name: &'static str,
    computed: Result<String, String>,
}

impl DisciplineAttempt {
    fn computed(name: &'static str, cid: String) -> Self {
        Self {
            name,
            computed: Ok(cid),
        }
    }

    fn failed(name: &'static str, reason: impl Into<String>) -> Self {
        Self {
            name,
            computed: Err(reason.into()),
        }
    }

    fn describe(&self) -> String {
        match &self.computed {
            Ok(cid) => format!("        {name}: {cid}", name = self.name),
            Err(reason) => format!("        {name}: {reason}", name = self.name),
        }
    }
}

fn parse_json(bytes: &[u8], discipline: &'static str) -> Result<Value, DisciplineAttempt> {
    serde_json::from_slice(bytes).map_err(|err| {
        DisciplineAttempt::failed(discipline, format!("invalid JSON for discipline: {err}"))
    })
}

fn object_without_fields(
    value: &Value,
    fields: &[&str],
    discipline: &'static str,
) -> Result<Value, DisciplineAttempt> {
    let Value::Object(map) = value else {
        return Err(DisciplineAttempt::failed(
            discipline,
            "expected top-level JSON object",
        ));
    };
    let mut map = map.clone();
    for field in fields {
        map.remove(*field);
    }
    Ok(Value::Object(map))
}

// Bind-inventory evidence and compound contracts were generated by
// implementations/rust/libsugar/src/compose.rs:1493 and :1582 under the rule
// CID(JCS(header with top-level cid elided)). Historical witness-consensus
// evidence used the same rule in
// bootstrap/scripts/run_libsugar_intra_vendor_consensus.sh:128.
fn bind_cid_elided_jcs(bytes: &[u8]) -> DisciplineAttempt {
    const NAME: &str = "bind cid-elided JCS";
    let value = match parse_json(bytes, NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    let value = match object_without_fields(&value, &["cid"], NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    DisciplineAttempt::computed(NAME, jcs_cid_of_json(&value))
}

// Promotion decisions are generated by
// implementations/rust/sugar-ir-types/src/lib.rs:1981 and :2003:
// recompute header.cid as CID(JCS(header with cid elided, evidence_cids sorted)).
fn promotion_header_cid(bytes: &[u8]) -> DisciplineAttempt {
    const NAME: &str = "promotion decision header JCS";
    let value = match parse_json(bytes, NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    let Some(header) = value.get("header") else {
        return DisciplineAttempt::failed(NAME, "missing header object");
    };
    let Value::Object(header_map) = header else {
        return DisciplineAttempt::failed(NAME, "header is not an object");
    };
    let mut header_map = header_map.clone();
    header_map.remove("cid");
    if let Some(Value::Array(evidence_cids)) = header_map.get_mut("evidence_cids") {
        evidence_cids.sort_by(|left, right| left.as_str().cmp(&right.as_str()));
    }
    DisciplineAttempt::computed(NAME, jcs_cid_of_json(&Value::Object(header_map)))
}

// Bind policies from the historical generator
// a4ee9d234:implementations/rust/provekit-cli/src/cmd_bind.rs:2397-2431 use
// CID(JCS(policy object)). A cid field, if a future policy grows one, is not
// part of that header rule and is elided before recomputation.
fn bind_policy_jcs(bytes: &[u8]) -> DisciplineAttempt {
    const NAME: &str = "bind policy JCS";
    let value = match parse_json(bytes, NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    let value = match object_without_fields(&value, &["cid"], NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    DisciplineAttempt::computed(NAME, jcs_cid_of_json(&value))
}

// Current sites are minted by
// implementations/rust/libsugar/src/core/bind.rs:1101 as
// CID(JCS({"name": name, "termShapeCid": term_shape_cid})).
fn current_bind_site_preimage(bytes: &[u8]) -> DisciplineAttempt {
    const NAME: &str = "current bind site preimage";
    let value = match parse_json(bytes, NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    let Value::Object(map) = &value else {
        return DisciplineAttempt::failed(NAME, "expected top-level JSON object");
    };
    let (Some(name), Some(term_shape_cid)) = (map.get("name"), map.get("termShapeCid")) else {
        return DisciplineAttempt::failed(NAME, "missing name or termShapeCid");
    };
    let mut preimage = Map::new();
    preimage.insert("name".to_string(), name.clone());
    preimage.insert("termShapeCid".to_string(), term_shape_cid.clone());
    DisciplineAttempt::computed(NAME, jcs_cid_of_json(&Value::Object(preimage)))
}

// Historical concept-site artifacts are sealed testimony from
// a4ee9d234:implementations/rust/provekit-cli/src/cmd_bind.rs:1127-1140. That
// generator hashed the site header before attaching cid, and before the later
// realization_mode_hint field existed, so both fields are elided here.
fn historical_bind_site_header(bytes: &[u8]) -> DisciplineAttempt {
    const NAME: &str = "historical bind site header JCS";
    let value = match parse_json(bytes, NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    let value = match object_without_fields(&value, &["cid", "realization_mode_hint"], NAME) {
        Ok(value) => value,
        Err(attempt) => return attempt,
    };
    DisciplineAttempt::computed(NAME, jcs_cid_of_json(&value))
}

fn raw_bytes(bytes: &[u8]) -> DisciplineAttempt {
    DisciplineAttempt::computed("raw bytes", blake3_512_of(bytes))
}

fn is_under(rel: &str, dir: &str) -> bool {
    rel.strip_prefix(dir)
        .is_some_and(|rest| !rest.is_empty() && !rest.contains('/'))
}

fn attempts_for(rel: &Path, bytes: &[u8]) -> Vec<DisciplineAttempt> {
    let rel = rel.to_string_lossy().replace('\\', "/");
    if is_under(&rel, "bootstrap/libsugar-bind-inventory/raw/contracts/")
        || is_under(&rel, "bootstrap/libsugar-bind-inventory/raw/evidence/")
        || is_under(
            &rel,
            "bootstrap/libsugar-bind-inventory/raw/evidence/witness-consensus/",
        )
    {
        vec![bind_cid_elided_jcs(bytes)]
    } else if is_under(&rel, "bootstrap/libsugar-bind-inventory/raw/policies/") {
        vec![bind_policy_jcs(bytes)]
    } else if is_under(
        &rel,
        "bootstrap/libsugar-bind-inventory/raw/promotion-decisions/",
    ) {
        vec![promotion_header_cid(bytes)]
    } else if is_under(&rel, "bootstrap/libsugar-bind-inventory/raw/sites/") {
        vec![
            current_bind_site_preimage(bytes),
            historical_bind_site_header(bytes),
        ]
    } else {
        vec![raw_bytes(bytes)]
    }
}

#[test]
fn every_committed_cid_named_file_hashes_to_its_filename() {
    let root = repo_root();
    let mut files = Vec::new();
    collect(&root, &mut files);
    assert!(
        !files.is_empty(),
        "found no CID-named artifacts under {} -- the scan is broken, not the tree",
        root.display()
    );

    let mut mismatches = Vec::new();
    let mut verified_by: BTreeMap<&'static str, usize> = BTreeMap::new();
    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let claimed = claimed_cid(&name).expect("collected only CID-named files");
        let bytes = fs::read(path).expect("read content-addressed artifact");
        let rel = path.strip_prefix(&root).unwrap_or(path);
        let attempts = attempts_for(rel, &bytes);
        if let Some(attempt) = attempts
            .iter()
            .find(|attempt| matches!(&attempt.computed, Ok(cid) if cid == &claimed))
        {
            *verified_by.entry(attempt.name).or_insert(0) += 1;
        } else {
            let attempted = attempts
                .iter()
                .map(DisciplineAttempt::describe)
                .collect::<Vec<_>>()
                .join("\n");
            mismatches.push(format!(
                "  {}\n      claims {claimed}\n      attempted disciplines:\n{attempted}",
                rel.display()
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} content-addressed artifact(s) no longer verify under their declared \
         content-address discipline. Their sealed content was edited under a fixed \
         CID name, or a class-specific generator rule was not modeled exactly. \
         Restore the original bytes or teach this gate the exact generator rule; \
         never add an exclusion:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );

    let counts = verified_by
        .iter()
        .map(|(discipline, count)| format!("{discipline}={count}"))
        .collect::<Vec<_>>()
        .join(", ");
    eprintln!(
        "integrity: {} content-addressed artifacts verified ({counts})",
        files.len(),
    );
}
