// SPDX-License-Identifier: Apache-2.0

use sugar_verifier::{
    ObligationVerdict, VerifyEffect, VerifyEffectBoundary, WitnessVerificationCheck,
    WitnessVerificationOutcome,
};

#[test]
fn verify_effect_lowering_is_the_single_legacy_reason_boundary() {
    let effect = VerifyEffect::MissingProvenanceKind {
        contract_cid: "blake3-512:contract".to_string(),
        property_name: "strings_consistency".to_string(),
        detail: "contract memento lacks required proofirProvenance/sourceWarrants provenance KIND"
            .to_string(),
    };

    let boundary: VerifyEffectBoundary = effect.to_legacy_boundary();

    assert_eq!(boundary.verdict, ObligationVerdict::Refused);
    assert_eq!(
        boundary.reason,
        effect.to_string(),
        "the legacy reason string must be generated by VerifyEffect Display only"
    );
    assert_eq!(
        boundary.verification.as_ref().and_then(|v| v.get("reason")),
        Some(&serde_json::Value::String(boundary.reason.clone())),
        "the JSON boundary must reuse the same generated reason"
    );
}

#[test]
fn witness_verification_outcome_lowers_without_stringly_status_fields() {
    let effect = VerifyEffect::WitnessVerification {
        witness_cid: "blake3-512:witness".to_string(),
        check: WitnessVerificationCheck::InvalidSignature,
    };
    let outcome = WitnessVerificationOutcome::Refused(effect.clone());

    assert!(!outcome.is_ok());
    assert_eq!(outcome.verdict(), "refused");
    assert_eq!(outcome.reason(), effect.to_string());
}
